import type { Metadata } from "next";
import { IM_Fell_Great_Primer_SC, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
});

const imFell = IM_Fell_Great_Primer_SC({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${imFell.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
